### ISSUE TITLE
DHCP hierarchical failover

### ISSUE THREAD

**Issue by FletchFFletch9** [aredn/aredn#123]
Consider having a delay time option on the LAN DHCP server so there is a hierarchical failover should the primary DHCP server go down. I think this is important for emergency communications. I had this problem working in our EOC where four nodes are tied together and three had the DCHP disabled. The primary node went down and I couldn't connect to the others while in the EOC because none of them were serving IP addresses.

**Comment by ae6xe** [comment]
I always leave DHCP on and not merge together the LAN networks of nodes on a switch.   This means every node connected to the switch would have a unique LAN vlan.   Turning DHCP off usually ends up with something not working, because the node is no longer a standard behavior and not reliably interchangeable -- at home, in the park, for an event, etc.  We forget DHCP is off and wondering why things aren't working.   If a DHCP server were to failover to another node, with their LAN networks munged together on the switch, while a node could be reached from the LAN, then the services advertisements would be broken.   There may still be something to fix.  If so, probably best to fix the original failure.

**Comment by FletchFFletch9** [comment]
That sounds reasonable. I suppose I could play DCHP roulette and just enable it on all the nodes and if I need a specific service on a specific node I can set a static IP address.

**Comment by ae6xe** [comment]
No need to play DHCP roulette if the switch is configured with a unique vlan ID for each node's LAN.  A port on the switch is configured to be on the LAN of only one given mesh node.    The node then has the service advertisement.    If this node fails, then fix this problem, or setup ports on the switch for a different mesh node and setup duplicate/failover service advertisements  --  fault tolerance at the service level.

**Comment by FletchFFletch9** [comment]
I'm using a dumb 5-port switch.

**Comment by ae6xe** [comment]
Unlikely to change how DHCP standard works, so closing this issue.
