### ISSUE TITLE
Favicon needed!

### ISSUE THREAD

**Issue by Orv** [aredn/aredn#1365]
Would be helpful to have a distinctive favicon for AREDN node web pages.
**Describe the solution you'd like**
Would be cool to have a mini version of the AREDN logo as a favicon, if possible.

**Comment by aanon4** [comment]
Does anyone have a favorite online favicon maker?

**Comment by VA2XJM** [comment]
https://realfavicongenerator.net/



Jean-Michel Vien - VA2XJM
Président, Association des Radioamateurs de l'Abitibi-Témiscamingue
https://www.ve2atu.org

**Comment by dman776** [comment]
favicon15 KBThanks,DarrylOn Aug 22, 2024, at 5:33 PM, Tim Wilkinson ***@***.***> wrote:﻿
Does anyone have a favorite online favicon maker?

**Comment by aanon4** [comment]
Thanks.

Looks like Firefox and Chrome support SVG favicons so we will go with that. Safari doesn't (my preferred browser) but I'm not carrying and loading an extra icon resources just for a browser which is 3 years behind everyone else on this. Hardly critical functionality.

Similarly, the favicon will be loaded from the localnode regardless of which node you're looking at on the network. This is how all resources work (it saves time and bandwidth) but I wont bother falling back to a network load because a nice icon is not critical.

**Comment by aanon4** [comment]
Checked in Firefox and Chrome (wont work on Safari because .. Apple)
