### ISSUE TITLE
Switching between UIs changes Tunnel Server IP Assignments

### ISSUE THREAD

**Issue by km6aow** [aredn/aredn#1378]
### Describe the bug
The IP address assigned to a user changes when switching between UIs.

- [ ] Does this issue still occur on the latest version? (**Required**) Yes - on version 20240823-c7d942a

### Expected behavior
I expect the tunnel IP addresses to remain as originally assigned.

### Screenshots
![image](https://github.com/user-attachments/assets/b59bd01d-a12c-4ac5-8233-b3a70663005a)
![image](https://github.com/user-attachments/assets/27526c08-3e29-4077-8d3c-fdd0cb52b1ee)
![image](https://github.com/user-attachments/assets/d90e6f64-2595-46f6-88bd-f72f70130796)

### Additional context
Note that the IP address 172.31.81.120 was assigned to KG6JHT under the old UI, and to WA6BXV under the new.

**Comment by aanon4** [comment]
Please attach the support data. Thanks.

**Comment by aanon4** [comment]
Also, it WA6BXV-NOVATO-HAP really in here three times?

**Comment by km6aow** [comment]
I've asked him for the support data and will attach it when I get it. As for BXV, he said he made those additional entries to try to associate the correct IP address with the user after they changed. The table kept growning and he sees no way to delete obsolete entries.

**Comment by km6aow** [comment]
[supportdata-AB6JR-Novato-hAP3-2024-8-24-7-35.tar.gz](https://github.com/user-attachments/files/16739008/supportdata-AB6JR-Novato-hAP3-2024-8-24-7-35.tar.gz)

**Comment by aanon4** [comment]
Short version - the new UI is correct.
Longer version -
The new UI reads exactly what's in the config file for tunnels and display that information on the screen. The old UI reads the entries in order and assigned an IP address to each entry it displays based on the order it was read. That has been fine because the old UI always read and rewrote the entire list every time, so the order stayed the same. The new UI doesnt do that, instead using the information stored and only writing changes. The consequence of this is that, once the new UI has modified the tunnels, the tunnel order may no longer be the same, so the old UI will get it wrong.  There's not much to be done here because we have new features - like being able to delete tunnels - and the old UI just can't support this and get's confused.

**Comment by aanon4** [comment]
Adding a warning: https://github.com/aredn/aredn/pull/1440
