### ISSUE TITLE
Meshchat download does not work

### ISSUE THREAD

**Issue by KQ6EO** [aredn/aredn#1576]
### Describe the bug
Nightly upgrade (20240925-e8fb21d )removed Meshchat from the node.  The Meshchat api was still there.  Removed api and tried to reload but received the error message shown in the screenshot.

![image](https://github.com/user-attachments/assets/b5065559-36e1-4ff0-bbad-40a3648ecd51)

**Comment by aanon4** [comment]
How did you get "meshchat" to show up in the Downloads selector?

**Comment by edkraus** [comment]
FWIW, I have one node with 20240906-f5ef0ec on it.  It was a bear to get the service packages to work, they did not auto install on the new UI.  I ended up deleting them and re-installing them after the new UI was working.  I however only install packages from my local machine, I never ask a node to install direct from some repository.  I keep all the latest firmware and packages I need in folders on my hard drive.  I don't know if your error is because trying to skip a step (download to local first) or if the newer nightly created the issue.    Ed

**Comment by aanon4** [comment]
Closing as there has been no follow up.

**Comment by edkraus** [comment]
the issue was with an early version of new UI, current release 3.24.10.0 did an automatic re-install of packages correctly.
Ed

    On Friday, October 4, 2024 at 03:43:58 PM PDT, Tim Wilkinson ***@***.***> wrote:  
 
 


Closing as there has been no follow up.
