### ISSUE TITLE
Preventing LAN devices from accessing WAN doesn't work completely

### ISSUE THREAD

**Issue by n4tqu** [aredn/aredn#26]
I upgraded to 3.19.3.0 today and decided to try the option for "Prevent LAN devices from accessing WAN" and noticed that this does not work as written. An existing LAN device will continue to access the WAN at least until the DHCP lease on the client renews and drops the default route. Also, anyone can add a static route on the LAN device and be capable of accessing the WAN.

I suggest an iptables rule would likely be more appropriate as a preventative measure.

Additionally, checking this box really should not require a restart of the mesh node. I suspect this is done due to limitations of the hardware however.

Steve - N4TQU

**Comment by WZ0C** [comment]
It would be preferable for the UI option wording to be for a positive decision rather than a negative decision.  That is, "Enable Default Route" rather than "Disable Default Route".  A user having to turn something on (the checkbox) to turn off the feature (default route) can lead to confusion, frustration, and misconfiguration.   And similarly, "Enable LAN device access to WAN", rather than "Disable LAN device access to WAN".
