### ISSUE TITLE
N-1835-1865 Doesn't show all Service Link information when selecting/searching as compared to the full list

### ISSUE THREAD

**Issue by k1ky** [aredn/aredn#530]
Bug: Service listings on older nodes running 3.16.2.0 (and probably earlier) don't show in the node list on nodes running Nightly 1835 (when selecting node filter) and the previous nightly that introduced the new sortable GUI feature.

**Comment by aanon4** [comment]
Could you post some screen shots? Specifically, a screen shot on the nightly showing the missing services, one on 3.22.8.0 showing the services, and one of the services on the 3.16.1.1 node.

**Comment by aanon4** [comment]
And if possible, support tool data for each of the nodes. I realize that might be difficult - but at least the nightly node and the 3.22.8.0 node.

**Comment by k1ky** [comment]
This is the N-1835 node screen shot.  The 3.16.1.1 node is KM4ACK NSM5XW node below that doesn't show the services:
<img width="799" alt="image" src="https://user-images.githubusercontent.com/42675931/197311317-5a41afad-09fa-4316-9b97-b247f5a9922d.png">

**Comment by aanon4** [comment]
Does it show the correct services when you're not filtering by its name, or only when you are?

**Comment by k1ky** [comment]
Actually it's the KM4ACK-ARHP-200 services that don't show:
Here is a view from a node running N-1757
<img width="554" alt="image" src="https://user-images.githubusercontent.com/42675931/197311439-cd4ad0cb-cf5e-442f-99b5-a736285a98c5.png">

**Comment by aanon4** [comment]
In your example, KM4ACK-ARHP-200 doesnt have any service directly hosted by the node. It does have services attached to LAN connected machines, but if you're using the node filtering option, these are not selected as they're not nodes.

**Comment by k1ky** [comment]
Support data files

> 

You are correct - If I don't use the "filter", the services display properly:
<img width="750" alt="image" src="https://user-images.githubusercontent.com/42675931/197313879-cd5961fa-21d7-4f0f-bb0d-0f24c6a79834.png">

**Comment by k1ky** [comment]
Support data with renamed extensions - one was a tgz and the other was gz.
[supportdata-KM4ACK-ARHP-200-LASCASSAS-202210212101.zip](https://github.com/aredn/aredn/files/9843341/supportdata-KM4ACK-ARHP-200-LASCASSAS-202210212101.zip)
[supportdata-K1KY-HAPA-450-P2-202210212100.zip](https://github.com/aredn/aredn/files/9843342/supportdata-K1KY-HAPA-450-P2-202210212100.zip)

**Comment by k1ky** [comment]
> 

Apparently it's only an issue when using the filter.  Maybe this is acceptable behavior and I just don't understand.  I figured it would still sow everything for the selected node.

**Comment by ab7pa** [comment]
The services you want to view seem to be provided by the LAN Hosts on that node.  If that is the case, then you could search in the **LAN Hostname** column for KM4ACK.  I can see, however, that even that search will not pick up everything because KM4ACK has not prefixed his LAN hostnames with his callsign.  According to the "best practice" suggestion in the online docs, even the LAN hostnames should be prefixed with the owner's callsign in order to give it a unique name across the entire mesh.  Hope this helps.
From the [Port Forwarding, DHCP, and Services](https://arednmesh.readthedocs.io/en/latest/arednGettingStarted/advanced_config.html#port-forwarding-dhcp-services-and-dns-aliases) section:
<img width="634" alt="Screen Shot 2022-10-21 at 7 13 40 PM" src="https://user-images.githubusercontent.com/69524416/197314831-e7fa0ee2-0c5e-472d-a5bb-bbe0d8ffdacd.png">

**Comment by k1ky** [comment]
Yes, that is correct.  All services and node information show when "not" sorting.  One would expect that it should show the same information when sorting?  I believe that is the issue that I was attempting to highlight.


    On Friday, October 21, 2022 at 08:54:46 PM CDT, Tim Wilkinson ***@***.***> wrote:  
 
 


Does it show the correct services when you're not filtering by its name, or only when you are?

**Comment by ab7pa** [comment]
@k1ky Tom, based on the screenshots you provided it appears that the **Mesh Status** column filtering feature is working exactly as intended.  The issue has nothing to do with which firmware version the remote nodes are running.  You asked the page to show you any node names containing "km4ack" and that's exactly what is shown in your screenshot.  
![Screenshot 2022-11-03 at 2 51 31 PM](https://user-images.githubusercontent.com/69524416/199841994-7c5cdb12-c8b8-4ed2-8899-20bb168295f7.png)

If you want to see the LAN services computers which have "km4ack" then you should search in the _LAN Hostname_ column.  Here is an example from my local mesh of searching in the _LAN Hostname_ column for service computers.  This works perfectly because this node owner properly prefixed his callsign to his service computer names.  If KM4ACK had prefixed his callsign to his service computers then you would have found all of them just like in this example.
![Screenshot 2022-11-03 at 3 05 39 PM](https://user-images.githubusercontent.com/69524416/199843383-74371b10-6e3d-483c-bd8b-d24b580e89e5.png)
