### ISSUE TITLE
Nightly Builds Download

### ISSUE THREAD

**Issue by kc2cbd** [aredn/aredn#567]
Is it possible to add a Nightly Builds Download Box on the Administration Page?

**Comment by dman776** [comment]
not currently.   it would involve the manipulation of all of the ".list" files EVERY TIME a nightly build is run.

**Comment by dman776** [comment]
looking into this further, more logic would be required because the "snapshots/nightlies" are stored in a different directory on the downloads server than the released firmware.  (including needing to know the architecture and subtype for the firmware.  ie.  /snapshots/targets/ath79/generic vs /snapshots/targets/ar71xx/mikrotik vs /firmware)
