### ISSUE TITLE
Schedule of firmware file updates

### ISSUE THREAD

**Issue by CoolAEW** [aredn/aredn#999]
### What is your question

How often do you update the files available for download on the website?
I'd like to try out some of the new features that was merged earlier this week, but they don't seem to be live on the latest firmware batch. The files available are from 04.12.23

### Links and screenshots

http://downloads.arednmesh.org/firmware/

### Additional context
_Add any other context about the problem here._

**Comment by aanon4** [comment]
Are you referring to some PRs that were pending until yesterday?

**Comment by dman776** [comment]
Files are available via downloads.arednmesh.org/afs/wwwThanks,DarrylOn Dec 7, 2023, at 4:28 PM, CoolAEW ***@***.***> wrote:﻿
What is your question
Describe your question/problem as clearly as possible.
How often do you update the files available for download on the website?
I'd like to try out some of the new features that was merged earlier this week, but they don't seem to be live on the latest firmware batch. The files available are from 04.12.23
Links and screenshots
Please include any relevant links or screenshots, if applicable.
http://downloads.arednmesh.org/firmware/
Additional context
Add any other context about the problem here.

**Comment by CoolAEW** [comment]
Ahh, ok.
Then I misunderstood how the releases worked.
I'll just wait for the next nightly 😊
